  GNU nano 7.2                          /etc/apache2/sites-available/vaultwarden.conf
<VirtualHost *:443>
    ServerName paroolihaldur.slillep.local

    SSLEngine on
    SSLCertificateFile /etc/ssl/localcerts/paroolihaldus.crt
    SSLCertificateKeyFile /etc/ssl/localcerts/paroolihaldus.key

    ProxyPreserveHost On
    ProxyPass / http://10.0.55.11:8080/
    ProxyPassReverse / http://10.0.55.11:8080/

    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Port "443"

    ErrorLog ${APACHE_LOG_DIR}/vaultwarden_error.log
    CustomLog ${APACHE_LOG_DIR}/vaultwarden_access.log combined
</VirtualHost>
